_target_: lightning.pytorch.trainer.Trainer
accelerator: gpu
devices: auto
strategy: auto
fast_dev_run: False
detect_anomaly: False
overfit_batches: 0
gradient_clip_val: 1 # set to 0 for no clip
gradient_clip_algorithm: norm
max_epochs: 1
val_check_interval: 1000  
check_val_every_n_epoch: 1
enable_progress_bar: False
inference_mode: False