_target_: src.model.omol_module.GraphModel

net: 
  _target_: nets.egnn.model.MC_EGNN
  hidden_channels: 1024
  in_edge_nf: 136 
  act_fn: 
    _target_: torch.nn.SiLU
  n_layers: 5 
  residual: True 
  attention: False 
  normalize: True
  tanh: True ### for stability but may decrease accuracy 
  max_atom_type: 100 
  cutoff: 6.0
  max_num_neighbors: 30
  use_pbc: False
  init_std: 0.02
  coords_weight: 1.0 
  num_vectors: 8 
  direct_forces: True

base_net: 
  _target_: nets.egnn.model.MC_EGNN
  hidden_channels: 256
  in_edge_nf: 136 
  act_fn: 
    _target_: torch.nn.SiLU
  n_layers: 5 
  residual: True 
  attention: False 
  normalize: True
  tanh: True ### for stability but may decrease accuracy 
  max_atom_type: 100 
  cutoff: 6.0
  max_num_neighbors: 30
  use_pbc: False
  init_std: 0.02
  coords_weight: 1.0 
  num_vectors: 8 
  direct_forces: True

optimizer:
  name: from_mup
  lr: 1e-4
  weight_decay: 0.0
  lr_min: 1e-6
  e_loss_name: per_atom_mae
  f_loss_name: l2norm
  e_weight: 10
  f_weight: 10
  amsgrad: False
  scheduler_name: cosine_annealing_ws
  T_max: 1
  num_warmup_steps: 10000
  num_restarts: 10

train_augmentation: False
compile: False
reference_path: configs/constants/element_refs.yaml

train_mean: 3.253
train_rmsd: 6.383
flops_coef: 81
