_target_: src.model.omol_module.GraphModel

net: 
  _target_: nets.faenet.model.FAENet
  hidden_channels: 128
  preprocess: base_preprocess
  num_filters: 480
  num_interactions: 5
  num_gaussians: 136
  regress_forces: direct
  max_num_neighbors: 30
  energy_head: False  # Energy head: {False, weighted-av-initial-embeds, weighted-av-final-embeds}
  skip_co: False  # Skip connections {False, "add", "concat"}
  second_layer_MLP: False  # in EmbeddingBlock
  complex_mp: True  # 2-layer MLP in Interaction blocks
  mp_type: simple  # Message Passing type {'base', 'simple', 'updownscale', 'updownscale_base'}
  graph_norm: True  # graph normalization layer
  equigrad: False
  force_decoder_type: "linear" # force head (`"simple"`, `"mlp"`, `"res"`, `"res_updown"`)
  force_decoder_model_config:
    linear: 
      hidden_channels: 
    simple:
      hidden_channels: 128
      norm: batch1d # batch1d, layer or null
    mlp:
      hidden_channels: 256
      norm: batch1d # batch1d, layer or null
    res:
      hidden_channels: 128
      norm: batch1d # batch1d, layer or null
    res_updown:
      hidden_channels: 128
      norm: batch1d # batch1d, layer or null
  
base_net:
  _target_: nets.faenet.model.FAENet
  hidden_channels: 128
  preprocess: base_preprocess
  num_filters: 480
  num_interactions: 5
  num_gaussians: 136
  regress_forces: direct
  max_num_neighbors: 30
  energy_head: False  # Energy head: {False, weighted-av-initial-embeds, weighted-av-final-embeds}
  skip_co: False  # Skip connections {False, "add", "concat"}
  second_layer_MLP: False  # in EmbeddingBlock
  complex_mp: True  # 2-layer MLP in Interaction blocks
  mp_type: simple  # Message Passing type {'base', 'simple', 'updownscale', 'updownscale_base'}
  graph_norm: True  # graph normalization layer
  equigrad: False
  force_decoder_type: "linear" # force head (`"simple"`, `"mlp"`, `"res"`, `"res_updown"`)
  force_decoder_model_config:
    linear: 
      hidden_channels: 
    simple:
      hidden_channels: 128
      norm: batch1d # batch1d, layer or null
    mlp:
      hidden_channels: 256
      norm: batch1d # batch1d, layer or null
    res:
      hidden_channels: 128
      norm: batch1d # batch1d, layer or null
    res_updown:
      hidden_channels: 128
      norm: batch1d # batch1d, layer or null

optimizer:
  lr: 5e-4
  lr_min: 1e-6
  name: free 
  weight_decay: 0.0
  e_loss_name: per_atom_mae
  f_loss_name: l2norm
  e_weight: 10
  f_weight: 10
  amsgrad: False
  scheduler_name: cosine_annealing
  T_max: 1
  num_warmup_steps: 100
  num_restarts: 10

train_augmentation: False
compile: False
reference_path: configs/constants/element_refs.yaml

train_mean: 3.253
train_rmsd: 6.383
flops_coef: 6
