_target_: src.model.omol_module.GraphModel

net: 
  _target_: nets.uma.model.EquivariantNet
  max_num_elements: 100
  sphere_channels: 32
  lmax: 4
  mmax: 2
  grid_resolution: 
  num_sphere_samples: 128  # NOTE not used
  # NOTE: graph construction related, to remove
  otf_graph: True
  max_neighbors: 30
  cutoff: 6.0
  edge_channels: 8
  distance_function: gaussian
  num_distance_basis: 136
  direct_forces: True
  regress_forces: True
  regress_stress: False
  # escnmd specific
  num_layers: 12
  hidden_channels: 32
  norm_type: rms_norm_sh
  act_type: gate
  ff_type: grid
  activation_checkpointing: False
  chg_spin_emb_type: pos_emb
  cs_emb_grad: False
  dataset_emb_grad: False
  dataset_list: 
  use_dataset_embedding: False
  use_cuda_graph_wigner: False
  radius_pbc_version: 1
  always_use_pbc: False

base_net: 
  _target_: nets.uma.model.EquivariantNet
  max_num_elements: 100
  sphere_channels: 32
  lmax: 4
  mmax: 2
  grid_resolution: 
  num_sphere_samples: 128  # NOTE not used
  # NOTE: graph construction related, to remove
  otf_graph: True
  max_neighbors: 30
  cutoff: 6.0
  edge_channels: 8
  distance_function: gaussian
  num_distance_basis: 136
  direct_forces: True
  regress_forces: True
  regress_stress: False
  # escnmd specific
  num_layers: 12
  hidden_channels: 32
  norm_type: rms_norm_sh
  act_type: gate
  ff_type: grid
  activation_checkpointing: False
  chg_spin_emb_type: pos_emb
  cs_emb_grad: False
  dataset_emb_grad: False
  dataset_list: 
  use_dataset_embedding: False
  use_cuda_graph_wigner: False
  radius_pbc_version: 1
  always_use_pbc: False


optimizer:
  lr: 5e-4
  lr_min: 1e-6
  name: free 
  weight_decay: 0.0
  e_loss_name: per_atom_mae
  f_loss_name: l2norm
  e_weight: 10
  f_weight: 10
  amsgrad: False
  scheduler_name: cosine_annealing
  T_max: 1
  num_warmup_steps: 100
  num_restarts: 10

train_augmentation: False
compile: False
reference_path: configs/constants/element_refs.yaml

train_mean: 3.253
train_rmsd: 6.383
flops_coef: 240
